//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inserted data is not valid.
        /// </summary>
        public static string ClientErrorData {
            get {
                return ResourceManager.GetString("ClientErrorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country has been added successfully!.
        /// </summary>
        public static string CountryAdded {
            get {
                return ResourceManager.GetString("CountryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country has been deleted successfully!.
        /// </summary>
        public static string CountryDeleted {
            get {
                return ResourceManager.GetString("CountryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country has been updated successfully!.
        /// </summary>
        public static string CountryUpdated {
            get {
                return ResourceManager.GetString("CountryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The department has been added successfully!.
        /// </summary>
        public static string DepartmentAdded {
            get {
                return ResourceManager.GetString("DepartmentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The department has been deleted successfully!.
        /// </summary>
        public static string DepartmentDeleted {
            get {
                return ResourceManager.GetString("DepartmentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The department has been updated successfully!.
        /// </summary>
        public static string DepartmentUpdated {
            get {
                return ResourceManager.GetString("DepartmentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee has been added successfully!.
        /// </summary>
        public static string EmployeeAdded {
            get {
                return ResourceManager.GetString("EmployeeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee has been deleted successfully!.
        /// </summary>
        public static string EmployeeDeleted {
            get {
                return ResourceManager.GetString("EmployeeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee has been updated successfully!.
        /// </summary>
        public static string EmployeeUpdated {
            get {
                return ResourceManager.GetString("EmployeeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found.
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete this item because there are employees linked with it.
        /// </summary>
        public static string ObjectLinkedWithEmployee {
            get {
                return ResourceManager.GetString("ObjectLinkedWithEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data entered does not exist.
        /// </summary>
        public static string ObjectNotFound {
            get {
                return ResourceManager.GetString("ObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected country id does not exist.
        /// </summary>
        public static string SelectedCountryIDNotExist {
            get {
                return ResourceManager.GetString("SelectedCountryIDNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected department id does not exist.
        /// </summary>
        public static string SelectedDepartmentIDNotExist {
            get {
                return ResourceManager.GetString("SelectedDepartmentIDNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        public static string ValidationErrorMessage_InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("ValidationErrorMessage_InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length is 100 digit.
        /// </summary>
        public static string ValidationErrorMessage_MaxString100 {
            get {
                return ResourceManager.GetString("ValidationErrorMessage_MaxString100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length is 50 digit.
        /// </summary>
        public static string ValidationErrorMessage_MaxString50 {
            get {
                return ResourceManager.GetString("ValidationErrorMessage_MaxString50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inserted number is out of range.
        /// </summary>
        public static string ValidationErrorMessage_OutOfRangeNumber {
            get {
                return ResourceManager.GetString("ValidationErrorMessage_OutOfRangeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string ValidationErrorMessage_RequiredValue {
            get {
                return ResourceManager.GetString("ValidationErrorMessage_RequiredValue", resourceCulture);
            }
        }
    }
}
